### ISSUE TITLE
getTaskResult returns stringify'd ints for koji_builds

### ISSUE THREAD

**Issue by ktdreyer** [containerbuildsystem/koji-containerbuild#217]
The `buildContainer` task result has a `koji_builds` list. The elements in this list are stringify'd ints, rather than plain ints.

This makes it complicated to pass those build IDs back into Koji, like the `listTags()` RPC will fail because "string" means "Name-Version-Release", not a build ID, and it's difficult to tell from the server-side backtrace what has failed.

Here's an example:

```
koji --noauth call getTaskResult --json 71079852
{
  "repositories": [
    "candidate-registry.fedoraproject.org/grafana:7-3",
    "candidate-registry.fedoraproject.org/grafana:rawhide-container-candidate-64151-20210630140646",
    "candidate-registry.fedoraproject.org/grafana:latest",
    "candidate-registry.fedoraproject.org/grafana:7"
  ],
  "koji_builds": [
    "1776886"
  ]
}
```

The `"1776886"` value is in quotes because it's a string.

**Comment by MartinBasti** [comment]
Yeah, it makes more sense, but we are afraid this is incompatible change and may break other people workflows. We would like to avoid adding new attr to keep compatibility, given how easy is workaround.

We don't want to address this issue.
