### ISSUE TITLE
consider relaxing jsonschema 3.2.0 requirement

### ISSUE THREAD

**Issue by nirik** [containerbuildsystem/koji-containerbuild#242]
Fedora rawhide has moved up to 4.6, leaving this package non-installable 
(see: https://bugzilla.redhat.com/show_bug.cgi?id=2101853 )

Looks like this was pinned to avoid a alpha version breaking python2 in https://github.com/containerbuildsystem/koji-containerbuild/commit/eb1aac6fa045daf9e0fa0449b6aaa4172293e450

**Comment by MartinBasti** [comment]
Well, we don't need py2 support in master branch, but still we need it in older version of koji-c which is still in active use. Would be enough to do this change only in master and fedora can patch it in dist-git ?

**Comment by nirik** [comment]
Sure, sounds reasonable.
